// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1/orchestrator.proto

package orchionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeStatus represents the current status of a node
type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED  NodeStatus = 0
	NodeStatus_NODE_STATUS_ACTIVE       NodeStatus = 1
	NodeStatus_NODE_STATUS_INACTIVE     NodeStatus = 2
	NodeStatus_NODE_STATUS_DISCONNECTED NodeStatus = 3
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_ACTIVE",
		2: "NODE_STATUS_INACTIVE",
		3: "NODE_STATUS_DISCONNECTED",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED":  0,
		"NODE_STATUS_ACTIVE":       1,
		"NODE_STATUS_INACTIVE":     2,
		"NODE_STATUS_DISCONNECTED": 3,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_orchestrator_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_orchestrator_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_orchestrator_proto_rawDescGZIP(), []int{0}
}

// NodeInfo contains information about a registered node
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        NodeStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=orchion.v1.NodeStatus" json:"status,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NodeInfo) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *NodeInfo) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *NodeInfo) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

// RegisterNodeRequest is the request to register a new node
type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterNodeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RegisterNodeResponse contains the newly assigned node ID
type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// HeartbeatRequest is sent by nodes to indicate they are alive
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// HeartbeatResponse acknowledges the heartbeat
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// UnregisterNodeRequest removes a node from the orchestrator
type UnregisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterNodeRequest) Reset() {
	*x = UnregisterNodeRequest{}
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterNodeRequest) ProtoMessage() {}

func (x *UnregisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterNodeRequest.ProtoReflect.Descriptor instead.
func (*UnregisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// UnregisterNodeResponse confirms node removal
type UnregisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterNodeResponse) Reset() {
	*x = UnregisterNodeResponse{}
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterNodeResponse) ProtoMessage() {}

func (x *UnregisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterNodeResponse.ProtoReflect.Descriptor instead.
func (*UnregisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *UnregisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListNodesRequest is the request to list all nodes
type ListNodesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by status (optional)
	StatusFilter  NodeStatus `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=orchion.v1.NodeStatus" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *ListNodesRequest) GetStatusFilter() NodeStatus {
	if x != nil {
		return x.StatusFilter
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

// ListNodesResponse returns all registered nodes
type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *ListNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_api_proto_v1_orchestrator_proto protoreflect.FileDescriptor

const file_api_proto_v1_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/v1/orchestrator.proto\x12\n" +
	"orchion.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x02\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12>\n" +
	"\bmetadata\x18\x03 \x03(\v2\".orchion.v1.NodeInfo.MetadataEntryR\bmetadata\x12.\n" +
	"\x06status\x18\x04 \x01(\x0e2\x16.orchion.v1.NodeStatusR\x06status\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12A\n" +
	"\x0elast_heartbeat\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\x13RegisterNodeRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12I\n" +
	"\bmetadata\x18\x02 \x03(\v2-.orchion.v1.RegisterNodeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x14RegisterNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"+\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"0\n" +
	"\x15UnregisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"2\n" +
	"\x16UnregisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"O\n" +
	"\x10ListNodesRequest\x12;\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x16.orchion.v1.NodeStatusR\fstatusFilter\"?\n" +
	"\x11ListNodesResponse\x12*\n" +
	"\x05nodes\x18\x01 \x03(\v2\x14.orchion.v1.NodeInfoR\x05nodes*y\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14NODE_STATUS_INACTIVE\x10\x02\x12\x1c\n" +
	"\x18NODE_STATUS_DISCONNECTED\x10\x032\xd5\x02\n" +
	"\x13OrchestratorService\x12Q\n" +
	"\fRegisterNode\x12\x1f.orchion.v1.RegisterNodeRequest\x1a .orchion.v1.RegisterNodeResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.orchion.v1.HeartbeatRequest\x1a\x1d.orchion.v1.HeartbeatResponse\x12W\n" +
	"\x0eUnregisterNode\x12!.orchion.v1.UnregisterNodeRequest\x1a\".orchion.v1.UnregisterNodeResponse\x12H\n" +
	"\tListNodes\x12\x1c.orchion.v1.ListNodesRequest\x1a\x1d.orchion.v1.ListNodesResponseB3Z1github.com/Orchion/Orchion/api/proto/v1;orchionv1b\x06proto3"

var (
	file_api_proto_v1_orchestrator_proto_rawDescOnce sync.Once
	file_api_proto_v1_orchestrator_proto_rawDescData []byte
)

func file_api_proto_v1_orchestrator_proto_rawDescGZIP() []byte {
	file_api_proto_v1_orchestrator_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_orchestrator_proto_rawDesc), len(file_api_proto_v1_orchestrator_proto_rawDesc)))
	})
	return file_api_proto_v1_orchestrator_proto_rawDescData
}

var file_api_proto_v1_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_v1_orchestrator_proto_goTypes = []any{
	(NodeStatus)(0),                // 0: orchion.v1.NodeStatus
	(*NodeInfo)(nil),               // 1: orchion.v1.NodeInfo
	(*RegisterNodeRequest)(nil),    // 2: orchion.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),   // 3: orchion.v1.RegisterNodeResponse
	(*HeartbeatRequest)(nil),       // 4: orchion.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 5: orchion.v1.HeartbeatResponse
	(*UnregisterNodeRequest)(nil),  // 6: orchion.v1.UnregisterNodeRequest
	(*UnregisterNodeResponse)(nil), // 7: orchion.v1.UnregisterNodeResponse
	(*ListNodesRequest)(nil),       // 8: orchion.v1.ListNodesRequest
	(*ListNodesResponse)(nil),      // 9: orchion.v1.ListNodesResponse
	nil,                            // 10: orchion.v1.NodeInfo.MetadataEntry
	nil,                            // 11: orchion.v1.RegisterNodeRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_api_proto_v1_orchestrator_proto_depIdxs = []int32{
	10, // 0: orchion.v1.NodeInfo.metadata:type_name -> orchion.v1.NodeInfo.MetadataEntry
	0,  // 1: orchion.v1.NodeInfo.status:type_name -> orchion.v1.NodeStatus
	12, // 2: orchion.v1.NodeInfo.registered_at:type_name -> google.protobuf.Timestamp
	12, // 3: orchion.v1.NodeInfo.last_heartbeat:type_name -> google.protobuf.Timestamp
	11, // 4: orchion.v1.RegisterNodeRequest.metadata:type_name -> orchion.v1.RegisterNodeRequest.MetadataEntry
	0,  // 5: orchion.v1.ListNodesRequest.status_filter:type_name -> orchion.v1.NodeStatus
	1,  // 6: orchion.v1.ListNodesResponse.nodes:type_name -> orchion.v1.NodeInfo
	2,  // 7: orchion.v1.OrchestratorService.RegisterNode:input_type -> orchion.v1.RegisterNodeRequest
	4,  // 8: orchion.v1.OrchestratorService.Heartbeat:input_type -> orchion.v1.HeartbeatRequest
	6,  // 9: orchion.v1.OrchestratorService.UnregisterNode:input_type -> orchion.v1.UnregisterNodeRequest
	8,  // 10: orchion.v1.OrchestratorService.ListNodes:input_type -> orchion.v1.ListNodesRequest
	3,  // 11: orchion.v1.OrchestratorService.RegisterNode:output_type -> orchion.v1.RegisterNodeResponse
	5,  // 12: orchion.v1.OrchestratorService.Heartbeat:output_type -> orchion.v1.HeartbeatResponse
	7,  // 13: orchion.v1.OrchestratorService.UnregisterNode:output_type -> orchion.v1.UnregisterNodeResponse
	9,  // 14: orchion.v1.OrchestratorService.ListNodes:output_type -> orchion.v1.ListNodesResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_v1_orchestrator_proto_init() }
func file_api_proto_v1_orchestrator_proto_init() {
	if File_api_proto_v1_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_orchestrator_proto_rawDesc), len(file_api_proto_v1_orchestrator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_orchestrator_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_orchestrator_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_orchestrator_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_orchestrator_proto_msgTypes,
	}.Build()
	File_api_proto_v1_orchestrator_proto = out.File
	file_api_proto_v1_orchestrator_proto_goTypes = nil
	file_api_proto_v1_orchestrator_proto_depIdxs = nil
}
